---
title: "Technical Skill Assignment"
author: "Jacob Schwan"
date: "`r Sys.Date()`"
output: 
    html_document:
        df_print: paged
        code_download: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, message = F)
```

```{r data-wrangling}
library(dplyr)
library(tidyr)
library(stringr)
library(forcats)
library(purrr)
library(vroom)
library(gt)

# Download and combine data sets
high_url <- "https://www.federalreserve.gov/supervisionreg/files/cards-high-risk-2022.csv"
typical_url <- "https://www.federalreserve.gov/supervisionreg/files/cards-typical-risk-2022.csv"
low_url <- "https://www.federalreserve.gov/supervisionreg/files/cards-low-risk-2022.csv"

dl_data <- function(url) {
    save_file <- here::here(basename(url))
    if(!file.exists(save_file)) {
        download.file(url, save_file)
    } else {
        message(paste0(basename(url), " already exists."))
    }
    save_file
}

data_files <- c(high_url, typical_url, low_url) %>%
    map_chr(dl_data) %>%
    set_names(basename(.) %>%
                  str_extract("\\w+-risk"))

card_data <- data_files %>%
    map_dfr(vroom::vroom, .id = "risk_level")

# Create factor levels for summaries
card_data_fct <- card_data %>%
    mutate(creditcardtype_fct = factor(creditcardtype, 
                                       labels = c("General purpose", "Private label")),
           currentcreditlimit_fct = cut(x = currentcreditlimit,
                                        breaks = c(-Inf, 1500, 7500, Inf),
                                        labels = c("$1,500 and less", 
                                                   "$1,501-$7,500",
                                                   "Over $7,500")),
           dayspastdue_fct = cut(x = dayspastdue,
                                 breaks = c(-Inf, 29, Inf),
                                 labels = c("Current", "30+ Days past due")),
           producttype_fct = factor(producttype, 
                                    labels = c("Co-brand", "Other")),
           activeflag_fct = factor(activeflag, 
                                   labels = c("Open and active", "Other")),
           accountoriginationyear_fct = case_when(accountoriginationyear <= 2016 ~ "2016 and prior",
                                                  T ~ as.character(accountoriginationyear)) %>%
               as_factor(),
           monthendclosedrevokedflag_fct = factor(monthendclosedrevokedflag, 
                                                  labels = c("Open and active", "Other")),
           cycleendingbalance_fct = cut(cycleendingbalance,
                                        breaks = c(-Inf, 1000, 2000, 3000, 5000, 10000, Inf),
                                        labels = c("Under $1,000", 
                                                   "$1,000-$1,999",
                                                   "$2,000-$2,999",
                                                   "$3,000-$4,999",
                                                   "$5,000-$9,999",
                                                   "$10,000 and over"),
                                        right = FALSE),
           borrowerincome_fct = cut(borrowerincome,
                                    breaks = c(-Inf, 50000, 100000, Inf),
                                    labels = c("$50,000 and less", 
                                               "$50,001-$100,000", 
                                               "Over $100,000")),
           originalcreditlimit_fct = cut(originalcreditlimit,
                                        breaks = c(-Inf, 1500, 7500, Inf),
                                        labels = c("$1,500 and less", 
                                                   "$1,501-$7,500", 
                                                   "Over $7,500")),
           cycleendingretailapr_fct = cut(cycleendingretailapr,
                                          breaks = c(-Inf, 12, 15, 20, 24, Inf),
                                          labels = c("Under 12%",
                                                     "12%-14.99%",
                                                     "15%-19.99%",
                                                     "20%-23.99%",
                                                     "24% and over"),
                                          right = FALSE)
           ) 

# Pivot data and summarize each variable
card_summaries <- card_data_fct %>%
    select(cycleendingbalance, risk_level, ends_with("fct")) %>%
    pivot_longer(!c(cycleendingbalance, risk_level), names_to = "group", values_to = "variables") %>%
    group_by(risk_level, group, variables) %>%
    summarise(balance = sum(cycleendingbalance), .groups = "drop_last") %>%
    mutate(pct_balance = balance/sum(balance)) %>%
    ungroup() %>%
    select(-balance) %>%
    pivot_wider(names_from = risk_level,
                values_from = pct_balance,
                values_fill = 0) 
```

```{r summary-table}
# Create table using GT package
card_summaries %>%
    # Re-level combined factors so that "Other" appears after "Open and active"
    mutate(variables = fct_relevel(variables, "Other", after = 10)) %>%
    arrange(variables) %>%
    gt(rowname_col = "variables") %>%
    tab_header(title = "Table 37. Summary statistics of selected variables in the portfolios of hypothetical credit card accounts",
               subtitle = "Percent as a share of cycle ending balance, except as noted") %>%
    opt_align_table_header(align = "left") %>%
    tab_stubhead("Variables") %>%
    tab_row_group(label = "Interest rate at cycle end",
                  row = grep("cycleendingretailapr", group)) %>%
    tab_row_group(label = "Original credit limit",
                  row = grep("originalcreditlimit", group)) %>%
    tab_row_group(label = "Income at origination",
                  row = grep("borrowerincome", group)) %>%
    tab_row_group(label = "Cycle ending balance",
                  row = grep("cycleendingbalance", group)) %>%
    tab_row_group(label = "Month-end close status",
                  row = grep("monthend", group)) %>%
    tab_row_group(label = "Account origination year",
                  row = grep("originationyear", group)) %>%
    tab_row_group(label = "Month-end account status",
                  row = grep("activeflag", group)) %>%
    tab_row_group(label = "Product type",
                  row = grep("producttype", group)) %>%
    tab_row_group(label = "Days past due",
                  row = grep("dayspastdue", group)) %>%
    tab_row_group(label = "Current credit limit",
                  row = grep("currentcreditlimit", group)) %>%
    tab_row_group(label = "Credit card type",
                  row = grep("creditcardtype", group)
                  ) %>%
    cols_hide(c("group")) %>%
    cols_label(`high-risk` = "Higher-risk",
               `typical-risk` = "Typical",
               `low-risk` = "Lower-risk") %>%
    cols_move(c("typical-risk", "high-risk"),after = "low-risk") %>%
    cols_width(contains("risk") ~ pct(20)) %>%
    fmt_number(columns = contains("risk"),
               decimals = 2,
               scale_by = 100) %>%
    opt_table_lines(extent = "none") %>%
    opt_table_outline(color = "#00538D") %>%
    # Style header in blue w/ white text
    tab_style(style = list(cell_fill(color = "#00538D"),
                           cell_text(color = "white",
                                     weight = "bold")),
              locations = list(cells_title("title"),
                               cells_title("subtitle"))) %>%
    # Style column headers in gray with black text and border
    tab_style(style = list(cell_fill(color = "#E6E6E8"),
                           cell_text(color = "black", 
                                     align = "center"),
                           cell_borders(sides = "all",
                                        color = "#00538D",
                                        weight = px(1))),
              locations = list(cells_stubhead(), 
                               cells_column_labels(columns = everything()))) %>%
    # Add blue top/bottom border to all rows
    tab_style(style = list(cell_borders(sides = c("top", "bottom"),
                                        color = "#00538D",
                                        weight = px(1))),
              locations = list(cells_stub(),
                               cells_body(),
                               cells_row_groups()
                               )) %>%
    # Make variable group names blue and bold
    tab_style(style = list(cell_text(color = "#00538D",
                                      weight = "bold")),
              locations =  list(cells_row_groups(groups = everything()))) %>%
    # Left align variable column
    tab_style(style = list(cell_text(align = "left", indent = px(20))),
              locations = cells_stub()) %>%
    # Indent value columns
    tab_style(style = list(css("padding-right" = "65px")),
              locations = cells_body())
    

```


Source code available on [Github](https://github.com/jacobschwan/FRB_skills_assignment)